[package]
name = "tlsecho"
version = "0.1.0"
authors = ["Martin Barth <martin@senfdax.de>"]

[dependencies]
openssl = "0.10.5"
tokio = "0.1.3"
tokio-openssl = "0.2"
tokio-uds = { git = "https://github.com/Marwes/tokio-uds", rev = "905b18e1" }